name: 'Nextcloud'
description: |
  The self-hosted productivity platform that keeps you in control.
version: '20.0.0'
category: 'Collaboration'
maintainer: 'Johannes Schm√∂lz'
license: 'MIT License'
projectURL: 'https://github.com/jschmoelz/rancher-catalog'
